config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  
  namespace :cpanel do
    root :to => "users#index"
    resources :users
    resources :idols
    resources :boxes
    resources :cards
  end
  
  get 'agreement' => 'mobile#agreement'
  get 'privacy' => 'mobile#privacy'
  get 'support' => 'mobile#support'
  
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :base_url, :presence => true
  belongs_to :user, counter_cache: true
  has_many :tags, dependent: :destroy
  has_many :boxes, -> { distinct }, through: :tags
  has_and_belongs_to_many :users
  has_many :marks, dependent: :destroy
  has_many :idols, -> { distinct }, through: :marks
  
  default_scope { where(soft_delete: false) }
  
  def img_preview_url
    self.preview_url ? self.upyun_url+self.preview_url+"!preview" : "#"
  end
  
  def img_standard_url
    self.upyun_url+self.base_url+"!standard"
  end
  
  def img_small_url
    self.upyun_url+self.base_url+"!small"
  end
  
  def img_thumb_url
    self.upyun_url+self.base_url+"!thumbnail"
  end
  
  def img_info_url
    self.upyun_url+self.base_url+"!info"
  end
  
  def card_id
    (self.id + 1000000000).to_s
  end
  
  def reset_from_key
    items = self.key_url.split('/', 8)
    if items[4]
      idol = Idol.find_or_create_by(name: items[3])
      self.idols << idol if idol
      self.pack = items[2] if items[3]
      self.topic = items[4] if items[5]
      self.event = event_space_trim(items[5]) if items[6]
      self.source = items[6] if items[7]
      self.title = "数据来源："+self.source if self.source
      if self.topic
        box_topic = idol.boxes.find_by(name: self.topic)
        if !box_topic
          box_topic = idol.boxes.create(name: self.topic, box_type: "topic")
        end
        Tag.find_or_create_by(card_id: self.id, box_id: box_topic.id)
      end
      if self.event
        box_event = idol.boxes.find_by(name: self.event)
        if !box_event
          box_event = idol.boxes.create(name: self.event, box_type: "event")
        end
        Tag.find_or_create_by(card_id: self.id, box_id: box_topic.id)
      end
    end
  end

  
  protected
    def upyun_url
      "http://fanhe-photo.b0.upaiyun.com"
    end
    
    def event_space_trim(str)
      str.slice! 6,1 if str[6] == ' '
      str
    end
  
end

app/controllers/cpanel/application_controller.rb
# coding: utf-8
class Cpanel::ApplicationController < ApplicationController
  
  layout "cpanel"
  
  http_basic_authenticate_with name: "fanhe", password: "zqpm01"
  
end

app/controllers/cpanel/boxes_controller.rb
# coding: utf-8
class Cpanel::BoxesController < Cpanel::ApplicationController
  
  def index
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    if idol
      @boxes = idol.boxes.paginate :page => params[:page], :per_page => 30
    else
      @boxes = Box.paginate :page => params[:page], :per_page => 30
    end
  end
  
  def new
    @box = Box.new
  end
  
  def edit
    @box = Box.find params[:id]
  end
  
  def update
    @box = Box.find params[:id]
    
    if @box.update_attributes(params[:box].permit!)
      redirect_to(cpanel_boxes_path, :notice => '话题修改成功')
    else
      render :action => "edit"
    end
  end
  
  
  
end

app/controllers/cpanel/cards_controller.rb
# coding: utf-8
class Cpanel::CardsController < Cpanel::ApplicationController
  
  def index
    user = User.find(params[:user_id]) if params[:user_id]
    box = Box.find(params[:box_id]) if params[:box_id]
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    @cards = Card.order(created_at: :desc).paginate :page => params[:page], :per_page => 20
    @cards = user.cards.order(created_at: :desc).includes(:marks, :tags).paginate :page => params[:page], :per_page => 20 if user
    @cards = box.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if box
    @cards = idol.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if idol
  end
  
  def new
    @card = Card.new
    @policy = Base64.encode64({:bucket => 'fanhe-photo', :expiration => (Time.now().to_i + 3600), 'save-key' => "/cards/{filemd5}{.suffix}","allow-file-type" =>"jpg,png,jpeg","content-length-range" => "0,20480000"}.to_json).gsub("\n","")
    @signature = Digest::MD5.hexdigest(@policy+'&'+'ZLxp3SHTJ1R7flhOVQVWL0YGtdw=')
  end
  
  def edit
    @card = Card.find params[:id]
  end
  
  def update
    @card = Card.find params[:id]
    
    if @card.update_attributes(params[:card].permit!)
      redirect_to(cpanel_cards_path, :notice => '卡片修改成功')
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @card = Card.find params[:id]
    
    @card.update(soft_delete: true)
    redirect_to cpanel_cards_path, :notice => '卡片删除成功'
  end
  
end

app/controllers/cpanel/idols_controller.rb
# coding: utf-8
class Cpanel::IdolsController < Cpanel::ApplicationController
  
  def index
    @idols = Idol.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @idol = Idol.new
  end
  
  def edit
    @idol = Idol.find params[:id]
  end
  
  def create
    
    @idol = Idol.new(params[:idol])
    @idol.encrypted_password = Digest::MD5.hexdigest(@idol.encrypted_password)
    
    if @idol.save
      redirect_to(cpanel_idols_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @idol = Idol.find params[:id]
    
    if @idol.update_attributes(params[:idol].permit!)
      redirect_to(cpanel_idols_path, :notice => '偶像修改成功')
    else
      render :action => "edit"
    end
  end
  
end

app/controllers/cpanel/users_controller.rb
# coding: utf-8
class Cpanel::UsersController < Cpanel::ApplicationController
  
  def index
    @users = User.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find params[:id]
  end
  
  def create
    
    @user = User.new(params[:user].permit!)
    @user.encrypted_password = Digest::MD5.hexdigest(@user.encrypted_password)
    
    if @user.save
      redirect_to(cpanel_users_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @user = User.find params[:id]
    
    if @user.update_attributes(params[:user].permit!)
      redirect_to(cpanel_users_path, :notice => '用户修改成功')
    else
      render :action => "edit"
    end
    
  end
  
  def destroy
    @user = User.find params[:id]
    
    @user.destroy
    redirect_to cpanel_users_path, :notice => @user.name + '删除成功'
    
  end
  
end

app/views/cpanel/cards/_form.html.erb
<div class="container">
	<%= simple_form_for([:cpanel, @card]) do |f| %>
	<fieldset class="col-md-6 col-md-offset-3">
		<%= f.error_notification %>
		<%= f.input :title, :label => "标题" %>
		<%= f.input :base_url, :readonly => true, :label => "文件链接"%>
		<%= f.input :image_width, :readonly => true, :label => "图片宽度"%>
		<%= f.input :image_height, :readonly => true, :label => "图片高度"%>
		<%= f.input :image_type, :readonly => true, :label => "图片类型"%>
		<%= f.input :topic, :label => "事件" %>
		<%= f.input :event, :label => "活动" %>
		<%= f.input :source, :label => "来源" %>
		<div class="actions">
			<%= f.submit '保存', :class => "btn btn-primary btn-lg btn-block", :disable_with => '保存中' %>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/cpanel/cards/edit.html.erb
<%= render "form" %>

app/views/cpanel/cards/index.html.erb
<div class="container">
	<div class="row">
		<% @cards.each do |card| %>
		<div class="col-sm-4 col-md-3">
			<div class="thumbnail">
			<%= image_tag card.img_thumb_url%>
      		<div class="caption">
        		<p class="text-warning">偶像：<%= card.marks.map(&:name).join(', ') %></p>
        		<p class="text-primary">事件：<%= card.topic %></p>
        		<p class="text-success">时间活动：<%= card.event %></p>
        		<p class="text-info">来源：<%= card.source %></p>
        		<p class="text-danger">标签：<%= card.tags.map(&:name).join(', ') %></p>
        		<%= link_to "编辑", edit_cpanel_card_path(card), :class => "btn btn-primary"%>
        	    <%= link_to "删除", cpanel_card_path(card), :method => :delete, :data => {:confirm => '确定要删除卡片，该操作不可恢复'}, :class => "btn btn-default" %>
      		</div>
      		</div>
		</div>
		<% end %>
	</div>
	<%= will_paginate @cards, :class => "center-block" %>
</div>

app/views/cpanel/cards/new.html.erb
<%= render "form" %>