config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  
  namespace :cpanel do
    root :to => "users#index"
    resources :users
    resources :idols
    resources :boxes
    resources :cards
  end
  
  get 'agreement' => 'mobile#agreement'
  get 'privacy' => 'mobile#privacy'
  get 'support' => 'mobile#support'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :encrypted_password, presence: true
  validates :name, uniqueness: true
  has_many :cards, dependent: :nullify
  has_many :subscribes, dependent: :destroy
  has_many :boxes, -> { distinct }, through: :subscribes
  has_many :fans
  has_many :idols, -> { distinct }, through: :fans
  has_and_belongs_to_many :zans, -> { uniq }, class_name: "Card"
  has_and_belongs_to_many :followers, -> { uniq }, class_name: "User", foreign_key: "followee_id", join_table: "followees_followers", association_foreign_key: "follower_id"
  has_and_belongs_to_many :followees, -> { uniq }, class_name: "User", foreign_key: "follower_id", join_table: "followees_followers", association_foreign_key: "followee_id"
  
  def user_id
    (self.id + 2000000000).to_s
  end
  
  def add_favorite (value)
    if self.favorites
      self.update(favorites: self.favorites + "," + value) unless self.favorites_list.index(value)
    else
      self.update(favorites: value)
    end
  end
  
  def del_favorite (value)
    if self.favorites && self.favorites_list.index(value)
      list = self.favorites_list
      list.delete(value)
      self.update(favorites: list.join(","))
    end
  end

  def favorites_list
    self.favorites ? self.favorites.split(",") : []
  end
  
  # 重新生成 Private Token
  def update_private_token
    random_key = "#{SecureRandom.hex(10)}:#{self.id}"
    self.update(private_token: random_key)
    self.private_token
  end
  
  after_create :create_user_token
  def create_user_token
    #self.create_box(name: self.name, avatar_url: self.avatar_url, info: self.info, box_type: "user")
    self.update_private_token
  end
  
end

app/controllers/cpanel/application_controller.rb
# coding: utf-8
class Cpanel::ApplicationController < ApplicationController
  
  layout "cpanel"
  
  http_basic_authenticate_with name: "fanhe", password: "zqpm01"
  
end

app/controllers/cpanel/boxes_controller.rb
# coding: utf-8
class Cpanel::BoxesController < Cpanel::ApplicationController
  
  def index
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    if idol
      @boxes = idol.boxes.paginate :page => params[:page], :per_page => 30
    else
      @boxes = Box.paginate :page => params[:page], :per_page => 30
    end
  end
  
  def new
    @box = Box.new
  end
  
  def edit
    @box = Box.find params[:id]
  end
  
  def update
    @box = Box.find params[:id]
    
    if @box.update_attributes(params[:box].permit!)
      redirect_to(cpanel_boxes_path, :notice => '话题修改成功')
    else
      render :action => "edit"
    end
  end
  
  
  
end

app/controllers/cpanel/cards_controller.rb
# coding: utf-8
class Cpanel::CardsController < Cpanel::ApplicationController
  
  def index
    user = User.find(params[:user_id]) if params[:user_id]
    box = Box.find(params[:box_id]) if params[:box_id]
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    @cards = Card.order(created_at: :desc).paginate :page => params[:page], :per_page => 20
    @cards = user.cards.order(created_at: :desc).includes(:marks, :tags).paginate :page => params[:page], :per_page => 20 if user
    @cards = box.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if box
    @cards = idol.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if idol
  end
  
  def new
    @card = Card.new
    @policy = Base64.encode64({:bucket => 'fanhe-photo', :expiration => (Time.now().to_i + 3600), 'save-key' => "/cards/{filemd5}{.suffix}","allow-file-type" =>"jpg,png,jpeg","content-length-range" => "0,20480000"}.to_json).gsub("\n","")
    @signature = Digest::MD5.hexdigest(@policy+'&'+'ZLxp3SHTJ1R7flhOVQVWL0YGtdw=')
  end
  
  def edit
    @card = Card.find params[:id]
  end
  
  def update
    @card = Card.find params[:id]
    
    if @card.update_attributes(params[:card].permit!)
      redirect_to(cpanel_cards_path, :notice => '卡片修改成功')
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @card = Card.find params[:id]
    
    @card.update(soft_delete: true)
    redirect_to cpanel_cards_path, :notice => '卡片删除成功'
  end
  
end

app/controllers/cpanel/idols_controller.rb
# coding: utf-8
class Cpanel::IdolsController < Cpanel::ApplicationController
  
  def index
    @idols = Idol.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @idol = Idol.new
  end
  
  def edit
    @idol = Idol.find params[:id]
  end
  
  def create
    
    @idol = Idol.new(params[:idol])
    @idol.encrypted_password = Digest::MD5.hexdigest(@idol.encrypted_password)
    
    if @idol.save
      redirect_to(cpanel_idols_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @idol = Idol.find params[:id]
    
    if @idol.update_attributes(params[:idol].permit!)
      redirect_to(cpanel_idols_path, :notice => '偶像修改成功')
    else
      render :action => "edit"
    end
  end
  
end

app/controllers/cpanel/users_controller.rb
# coding: utf-8
class Cpanel::UsersController < Cpanel::ApplicationController
  
  def index
    @users = User.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find params[:id]
  end
  
  def create
    
    @user = User.new(params[:user].permit!)
    @user.encrypted_password = Digest::MD5.hexdigest(@user.encrypted_password)
    
    if @user.save
      redirect_to(cpanel_users_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @user = User.find params[:id]
    
    if @user.update_attributes(params[:user].permit!)
      redirect_to(cpanel_users_path, :notice => '用户修改成功')
    else
      render :action => "edit"
    end
    
  end
  
  def destroy
    @user = User.find params[:id]
    
    @user.destroy
    redirect_to cpanel_users_path, :notice => @user.name + '删除成功'
    
  end
  
end

app/views/cpanel/users/_form.html.erb
<div class="container">
	<%= simple_form_for([:cpanel, @user]) do |f| %>
	<fieldset class="col-md-6 col-md-offset-3">
		<%= f.error_notification %>
		<%= f.input :name, :label => "姓名" %>
		<%= f.input :mobile, :label => "手机" %>
		<%= f.input :encrypted_password, :label => "密码" %>
		<%= f.input :gender, :label => "性别" %>
		<%= f.input :address, :label => "地址" %>
		<%= f.input :birth_date, :label => "出生日期" %>
		<%= f.input :info, :label => "简介" %>
		<div class="actions">
			<%= f.submit '保存', :class => "btn btn-primary btn-lg btn-block", :disable_with => '保存中' %>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/cpanel/users/index.html.erb
<div class="container">
<fieldset class="col-md-8 col-md-offset-2">
<table class="table table-hover">
  <tr>
    <td>ID</td>
    <td>头像</td>
    <td>昵称</td>
    <td>手机</td>
    <td>性别</td>
    <td>卡片数</td>
    <td>密匙</td>
    <td>操作</td>
  </tr>

<% @users.each do |user| %>
  <tr>
  	<td><%= user.id %></td>
  	<td><%= image_tag user.avatar_url, :style => "width: 30px" %></td>
	<td><%= user.name %></td>
	<td><%= user.mobile %></td>
	<td><%= user.gender %></td>
	<td><%= link_to user.cards_count, cpanel_cards_path(user_id: user.id) %></td>
	<td><%= user.private_token %></td>
	<td>
	 <%= link_to "编辑", edit_cpanel_user_path(user), :title => "编辑" %>
	 <%= link_to "删除", cpanel_user_path(user), :method => :delete, :data => {:confirm => '确定要删除用户，该操作不可恢复'}, :title => "删除" %>
	</td>
  </tr>
<% end %>
</table>
<%= will_paginate @users %>
</fieldset>
</div>

app/views/cpanel/users/new.html.erb
<%= render "form" %>