config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  
  namespace :cpanel do
    root :to => "users#index"
    resources :users
    resources :idols
    resources :boxes
    resources :cards
  end
  
  get 'agreement' => 'mobile#agreement'
  get 'privacy' => 'mobile#privacy'
  get 'support' => 'mobile#support'
  
end

app/models/box.rb
class Box < ActiveRecord::Base
  
  validates :name, :presence => true
  has_many :tags
  has_many :cards, through: :tags
  has_many :subscribes
  has_many :users, through: :subscribes
  belongs_to :idol, counter_cache: true
  
  belongs_to :user
  
  def box_id
    (self.id + 3000000000).to_s
  end
  
  def line_1
    self.line ? self.line.splite("|",2)[0] : "######"
  end
  
  def line_2
    self.line ? self.line.splite("|",2)[1] : "XOXOXOXOXO"
  end
  
end

app/controllers/cpanel/application_controller.rb
# coding: utf-8
class Cpanel::ApplicationController < ApplicationController
  
  layout "cpanel"
  
  http_basic_authenticate_with name: "fanhe", password: "zqpm01"
  
end

app/controllers/cpanel/boxes_controller.rb
# coding: utf-8
class Cpanel::BoxesController < Cpanel::ApplicationController
  
  def index
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    if idol
      @boxes = idol.boxes.paginate :page => params[:page], :per_page => 30
    else
      @boxes = Box.paginate :page => params[:page], :per_page => 30
    end
  end
  
  def new
    @box = Box.new
  end
  
  def edit
    @box = Box.find params[:id]
  end
  
  def update
    @box = Box.find params[:id]
    
    if @box.update_attributes(params[:box].permit!)
      redirect_to(cpanel_boxes_path, :notice => '话题修改成功')
    else
      render :action => "edit"
    end
  end
  
  
  
end

app/controllers/cpanel/cards_controller.rb
# coding: utf-8
class Cpanel::CardsController < Cpanel::ApplicationController
  
  def index
    user = User.find(params[:user_id]) if params[:user_id]
    box = Box.find(params[:box_id]) if params[:box_id]
    idol = Idol.find(params[:idol_id]) if params[:idol_id]
    @cards = Card.order(created_at: :desc).paginate :page => params[:page], :per_page => 20
    @cards = user.cards.order(created_at: :desc).includes(:marks, :tags).paginate :page => params[:page], :per_page => 20 if user
    @cards = box.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if box
    @cards = idol.cards.order(created_at: :desc).paginate :page => params[:page], :per_page => 20 if idol
  end
  
  def new
    @card = Card.new
    @policy = Base64.encode64({:bucket => 'fanhe-photo', :expiration => (Time.now().to_i + 3600), 'save-key' => "/cards/{filemd5}{.suffix}","allow-file-type" =>"jpg,png,jpeg","content-length-range" => "0,20480000"}.to_json).gsub("\n","")
    @signature = Digest::MD5.hexdigest(@policy+'&'+'ZLxp3SHTJ1R7flhOVQVWL0YGtdw=')
  end
  
  def edit
    @card = Card.find params[:id]
  end
  
  def update
    @card = Card.find params[:id]
    
    if @card.update_attributes(params[:card].permit!)
      redirect_to(cpanel_cards_path, :notice => '卡片修改成功')
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @card = Card.find params[:id]
    
    @card.update(soft_delete: true)
    redirect_to cpanel_cards_path, :notice => '卡片删除成功'
  end
  
end

app/controllers/cpanel/idols_controller.rb
# coding: utf-8
class Cpanel::IdolsController < Cpanel::ApplicationController
  
  def index
    @idols = Idol.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @idol = Idol.new
  end
  
  def edit
    @idol = Idol.find params[:id]
  end
  
  def create
    
    @idol = Idol.new(params[:idol])
    @idol.encrypted_password = Digest::MD5.hexdigest(@idol.encrypted_password)
    
    if @idol.save
      redirect_to(cpanel_idols_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @idol = Idol.find params[:id]
    
    if @idol.update_attributes(params[:idol].permit!)
      redirect_to(cpanel_idols_path, :notice => '偶像修改成功')
    else
      render :action => "edit"
    end
  end
  
end

app/controllers/cpanel/users_controller.rb
# coding: utf-8
class Cpanel::UsersController < Cpanel::ApplicationController
  
  def index
    @users = User.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find params[:id]
  end
  
  def create
    
    @user = User.new(params[:user].permit!)
    @user.encrypted_password = Digest::MD5.hexdigest(@user.encrypted_password)
    
    if @user.save
      redirect_to(cpanel_users_path, :notice => '用户创建成功')
    else
      render :action => "new"
    end
    
  end
  
  def update
    @user = User.find params[:id]
    
    if @user.update_attributes(params[:user].permit!)
      redirect_to(cpanel_users_path, :notice => '用户修改成功')
    else
      render :action => "edit"
    end
    
  end
  
  def destroy
    @user = User.find params[:id]
    
    @user.destroy
    redirect_to cpanel_users_path, :notice => @user.name + '删除成功'
    
  end
  
end

app/views/cpanel/boxes/_form.html.erb
<div class="container">
	<%= simple_form_for([:cpanel, @box]) do |f| %>
	<fieldset class="col-md-6 col-md-offset-3">
		<%= f.error_notification %>
		<%= f.input :name, :label => "话题名称" %>
		<%= f.input :info, :label => "简介" %>
		<%= f.input :avatar_url, :label => "封面地址" %>
		<%= f.input :box_type, :label => "话题类型" %>
		<%= f.input :line, :label => "封面简介" %>
		<%= f.input :hit_count, :label => "浏览量" %>
		<%= %>
		<div class="actions">
			<%= f.submit '保存', :class => "btn btn-primary btn-lg btn-block", :disable_with => '保存中' %>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/cpanel/boxes/index.html.erb
<div class="container">
<fieldset class="col-md-8 col-md-offset-2">
<table class="table table-hover">
  <tr>
    <td>ID</td>
    <td>话题名称</td>
    <td>偶像</td>
    <td>话题类型</td>
    <td>订阅人数</td>
    <td>卡片数量</td>
    <td>浏览量</td>
    <td>操作</td>
  </tr>

<% @boxes.each do |box| %>
  <tr>
  	<td><%= box.id %></td>
	<td style="max-width: 200px"><%= box.name %></td>
	<td><%= box.idol.name%></td>
	<td><%= box.box_type %></td>
	<td><%= box.subscribes_count %></td>
	<td><%= link_to box.tags_count, cpanel_cards_path(box_id: box.id) %></td>
	<td><%= box.hit_count %></td>
	<td>
	 <%= link_to "编辑", edit_cpanel_box_path(box), :title => "编辑" %>
	</td>
  </tr>
<% end %>
</table>
<%= will_paginate @boxes %>
</fieldset>
</div>

app/views/cpanel/boxes/new.html.erb
<%= render "form" %>