config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  
  namespace :cpanel do
    root :to => "users#index"
    resources :users
    resources :idols
    resources :boxes
    resources :cards
  end
  
  get 'agreement' => 'mobile#agreement'
  get 'privacy' => 'mobile#privacy'
  get 'support' => 'mobile#support'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FanBoxWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cpanel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "饭盒的萌萌哒后台" %></title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="navbar-header">
      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".gh-nav-collapse">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      		</button>
      		<a class="navbar-brand" href="#">饭盒管理后台</a>
    	</div>
    	<div class="collapse navbar-collapse">
    		<ul class="nav navbar-nav navbar-right">
    		<li><a href="<%= cpanel_users_path %>">用户管理</a></li>
    		<li><a href="<%= cpanel_idols_path %>">偶像管理</a></li>
    		<li><a href="<%= cpanel_boxes_path %>">话题管理</a></li>
    		<li class="dropdown">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown">新建 <span class="caret"></span></a>
          		<ul class="dropdown-menu" role="menu">
            		<li><a href="<%= new_cpanel_idol_path %>">新建偶像</a></li>
            		<li><a href="<%= new_cpanel_box_path %>">新建话题</a></li>
            		<li><a href="<%= new_cpanel_user_path %>">新建用户</a></li>
          		</ul>
        </li>
    		</ul>
    	</div>
	</div>
	</nav>
	
	<div class="container">
	<% if notice %>
	<div data-alert class="alert alert-info col-md-8 col-md-offset-2" id="notice-panel">
		<%= notice %>
	</div>
	<% end %>
	<% if alert %>
	<div data-alert class="alert alert-danger col-md-8 col-md-offset-2" id="alert-panel">
		<%= alert %>
	</div>
	<% end %>
	</div>
	
	<%= yield %>
	
	<%= yield :scripts %>

</body>
</html>